-- Application Specific Codes 
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('USER-ROLE', 'EMPLOYEE', 'Employee for company who can request reimbursement');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('USER-ROLE', 'BENEFIT-COORDINATOR', 'User who handles reimbursement requests');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('USER-ROLE', 'SUPERVISOR', 'User who manages benefit coordinators');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('USER-ROLE', 'HEAD-SUPERVISOR', 'User who manages supervisors');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('DEPARTMENT', 'UNIVERSITY', 'Handles reimbursement requests for universities');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('DEPARTMENT', 'SEMINARS', 'Handles reimbursement requests for seminars');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('DEPARTMENT', 'CERTIFICATION-PREP', 'Handles reimbursement for certification preperations');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('DEPARTMENT', 'CERTIFICATION', 'Handles reimbursement for certifications');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('DEPARTMENT', 'TECH-TRAINING', 'Handles reimbursement for technology training');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('DEPARTMENT', 'OTHER', 'Handles exception reimbursement claims');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('REIMBURSEMENT-RATE', 'UNIVERSITY', '0.80');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('REIMBURSEMENT-RATE', 'SEMINARS', '0.60');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('REIMBURSEMENT-RATE', 'CERTIFICATION-PREP', '0.75');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('REIMBURSEMENT-RATE', 'CERTIFICATION', '1.0');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('REIMBURSEMENT-RATE', 'TECH-TRAINING', '0.90');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('REIMBURSEMENT-RATE', 'OTHER', '0.30');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('STATUS', 'NEW', 'New un-edited item');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('STATUS', 'PENDING', 'Item waiting for approval');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('STATUS', 'DENIED', 'Rejected item');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('STATUS', 'APPROVED', 'Accepted item');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('STATUS', 'AWARDED', 'Approved item');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('GRADE-FORMAT', 'A', '[100,90]');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('GRADE-FORMAT', 'B', '[89.99,80]');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('GRADE-FORMAT', 'C', '[79.99,70]');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('GRADE-FORMAT', 'D', '[69.99,60');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('GRADE-FORMAT', 'F', '[59.99,0]');


COMMIT;