-- Application Specific Codes 
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('USER-ROLE', 'EMPLOYEE', 'Employee for company who can request reimbursement');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('USER-ROLE', 'BENEFIT-COORDINATOR', 'User who handles reimbursement requests');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('USER-ROLE', 'SUPERVISOR', 'User who manages benefit coordinators');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('USER-ROLE', 'HEAD-SUPERVISOR', 'User who manages supervisors');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('DEPARTMENT', 'PAPER', 'Paper department');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('DEPARTMENT', 'PLASTIC', 'Plastics department');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('DEPARTMENT', 'IT', 'IT department');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('DEPARTMENT', 'TRAVEL', 'Travel Agency department');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('REIMBURSEMENT-RATE', 'UNIVERSITY', '0.80');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('REIMBURSEMENT-RATE', 'SEMINARS', '0.60');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('REIMBURSEMENT-RATE', 'CERTIFICATION-PREP', '0.75');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('REIMBURSEMENT-RATE', 'CERTIFICATION', '1.0');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('REIMBURSEMENT-RATE', 'TECH-TRAINING', '0.90');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('REIMBURSEMENT-RATE', 'OTHER', '0.30');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('STATUS', 'NEW', 'New un-edited item');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('STATUS', 'PENDING', 'Item waiting for approval');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('STATUS', 'DENIED', 'Rejected item');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('STATUS', 'APPROVED', 'Accepted item');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('STATUS', 'AWARDED', 'Approved item');

INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('GRADING-TYPE', 'STANDARD', 'A:[100,90],B:[89.99,80],C:[79.99,70],D:[69.99,60],F:[59.99,0]');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('GRADING-TYPE', 'PASS-FAIL', 'No grade, just marked as pass or fail');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('GRADING-TYPE', 'OTHER', 'Type not known by system');

INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('PRIORITY', 'HIGH', 'High Priority');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('PRIORITY', 'MEDIUM', 'Medium Priority');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('PRIORITY', 'LOW', 'Low Priority');

INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('MESSAGE-STATUS', 'NEW', 'Message is new, or response from recipient was made');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('MESSAGE-STATUS', 'OPENED', 'Message was viewed');
INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('MESSAGE-STATUS', 'DELETED', 'Message was deleted');

INSERT INTO CODE_LIST(CODE,VALUE,DESCRIPTION)VALUES('REIMBURSEMENT-LIMIT', '1000', 'User is allowed at most $1000.00 USD');

COMMIT;