SELECT usernames, passwords, ADMIN_TYPE_ID FROM (
    SELECT * FROM (
        SELECT * FROM  Credentials WHERE usernames = 'test' AND passwords = 'script'
    ) T1 JOIN Accounts ON T1.CREDENTIALS_ID = ACCOUNTS.CREDENTIALS_ID AND ACCOUNTS.ACCOUNT_TYPE_ID = 0 -- get any matching credentials
    JOIN Account_Type T2 ON ACCOUNTS.ACCOUNT_TYPE_ID = T2.ACCOUNT_TYPE_ID 
    JOIN ADMIN_ACCOUNT_JUNCTION T3 ON T3.ACCOUNT_ID = ACCOUNTS.ACCOUNT_ID
    JOIN ADMINS T4 ON T4.ADMIN_ID = T3.ADMIN_ID
);

SELECT * FROM ADMIN_TYPE;

