select 'DROP table', table_name, 'cascade constraints;' from user_tables;

-- Create tables
CREATE TABLE CRITERIA_TYPE (
    CRIT_TYPE_ID number(1),
    CRIT_TYPE VARCHAR2(20),
    CONSTRAINT PK_CRIT_TYPE PRIMARY KEY(CRIT_TYPE_ID)
);

CREATE TABLE CRITERIA (
    CRIT_ID number(6),
    CRIT_TYPE_ID number(1),
    attachment CLOB,
    CONSTRAINT PK_CRIT_ID PRIMARY KEY(CRIT_ID),
    CONSTRAINT FK_CRIT_CRIT_TYPE FOREIGN KEY (CRIT_TYPE_ID)
        REFERENCES CRITERIA_TYPE(CRIT_TYPE_ID)
);

CREATE TABLE DEPARTMENT_TYPE (
    DEPT_TYPE_ID number(1),
    DEPT_TYPE VARCHAR2(20),
    CONSTRAINT PK_DEPT_TYPE PRIMARY KEY(DEPT_TYPE_ID)
);

CREATE TABLE DEPARTMENT (
    DEPT_ID number(6),
    DEPT_TYPE_ID number(1),
    CONSTRAINT PK_DEPT_ID PRIMARY KEY (DEPT_ID),
    CONSTRAINT FK_DEPT_DEPT_TYPE FOREIGN KEY(DEPT_TYPE_ID)
        REFERENCES DEPARTMENT_TYPE (DEPT_TYPE_ID)
);

CREATE TABLE EMPLOYEE_TYPE (
    EMP_TYPE_ID number(1),
    EMP_TYPE VARCHAR(20),
    CONSTRAINT PK_EMP_TYPE PRIMARY KEY(EMP_TYPE_ID)
);

CREATE TABLE EMPLOYEE (
    EMP_ID number(6),
    EMP_TYPE_ID number(1),
    DEPT_ID number(6),
    CONSTRAINT PK_EMP_ID PRIMARY KEY (EMP_ID),
    CONSTRAINT FK_EMP_EMP_TYPE FOREIGN KEY (EMP_TYPE_ID)
        REFERENCES EMPLOYEE_TYPE (EMP_TYPE_ID),
    CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPT_ID)
        REFERENCES DEPARTMENT(DEPT_ID)
);

CREATE TABLE DEPARTMENT_HEAD (
    DEPT_ID number(6),
    DEPT_HEAD number(6),
    CONSTRAINT FK_DEPT_HEAD_DEPT FOREIGN KEY (DEPT_ID)
        REFERENCES DEPARTMENT (DEPT_ID),
    CONSTRAINT FK_DEPT_HEAD FOREIGN KEY (DEPT_HEAD)
        REFERENCES EMPLOYEE(EMP_ID)
);

CREATE TABLE EVENT_TYPE (
    EVENT_TYPE_ID number(1),
    EVENT_TYPE VARCHAR2(20),
    CONSTRAINT PK_EVENT_TYPE PRIMARY KEY (EVENT_TYPE_ID)
);

CREATE TABLE EVENT (
    EVENT_ID number(6),
    EVENT_TYPE_ID number(1),
    CRIT_ID number(6),
    CONSTRAINT PK_EVENT_ID PRIMARY KEY (EVENT_ID),
    CONSTRAINT FK_EVENT_TYPE_ID FOREIGN KEY (EVENT_TYPE_ID)
        REFERENCES EVENT_TYPE (EVENT_TYPE_ID),
    CONSTRAINT FK_EVENT_CRIT FOREIGN KEY (CRIT_ID)
        REFERENCES CRITERIA (CRIT_ID)
);

CREATE TABLE EMPLOYEE_EVENT_JUNCTION (
    EMP_ID number(6),
    EVENT_ID number(6),
    CONSTRAINT FK_EEJ_EMP FOREIGN KEY (EMP_ID)
        REFERENCES EMPLOYEE (EMP_ID),
    CONSTRAINT FK_EEJ_EVENT FOREIGN KEY (EVENT_ID)
        REFERENCES EVENT (EVENT_ID)
);

CREATE TABLE REQUEST_STATUS (
    REQ_STAT_ID number(1),
    REQ_STAT VARCHAR2(20),
    CONSTRAINT PK_REQ_STAT PRIMARY KEY(REQ_STAT_ID)
);

CREATE TABLE REQUEST (
    REQ_ID number(6),
    REQ_STAT_ID number(1),
    MSG_LINK VARCHAR2(100),
    CONSTRAINT PK_REQ_ID PRIMARY KEY (REQ_ID)
);

CREATE TABLE REQUEST_EVENT_JUNCTION (
    REQ_ID number(6),
    EVENT_ID number(6),
    CONSTRAINT FK_REJ_REQ FOREIGN KEY (REQ_ID)
        REFERENCES REQUEST (REQ_ID),
    CONSTRAINT FK_REJ_EVENT_ID FOREIGN KEY (EVENT_ID)
        REFERENCES EVENT (EVENT_ID)
);

CREATE TABLE REQUEST_EMPLOYEE_JUNCTION (
    REQ_ID number(6),
    EMP_ID number(6),
    CONSTRAINT FK_REMPJ_REQ FOREIGN KEY (REQ_ID)
        REFERENCES REQUEST(REQ_ID),
    CONSTRAINT FK_REMPJ_EMP FOREIGN KEY (EMP_ID)
        REFERENCES EMPLOYEE (EMP_ID)
);