
package com.revature.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.revature.exceptions.soap.SOAPException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHelloWorld", targetNamespace = "http://ws.revature.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IHelloWorld {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHelloWorldAsString", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.GetHelloWorldAsString")
    @ResponseWrapper(localName = "getHelloWorldAsStringResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.GetHelloWorldAsStringResponse")
    @Action(input = "http://ws.revature.com/IHelloWorld/getHelloWorldAsStringRequest", output = "http://ws.revature.com/IHelloWorld/getHelloWorldAsStringResponse")
    public String getHelloWorldAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0) throws SOAPException;

}
